version: 0.1

environment_variables:
  plaintext:
    HUGO_VERSION: "0.82.1"
    
phases:
  install:
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v0.82.1/hugo_extended_0.82.1_Linux-64bit.tar.gz
      - tar -xzf hugo_extended_0.82.1_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd 
      - rm -rf /tmp/*
  build:
    commands:
      - cd /home/ec2-user/environment/quicksite
      - rm -rf public
      - hugo 
      - hugo deploy
  post_build:
    commands:
      - aws s3 sync --delete public s3://hugo-cd-aws
      - echo Build completed on `date`
